### PR TITLE
Adding mixed bechmarks

### LINKED ISSUE #5: Mixed benchmark
I'd be interested to see a benchmark for, say, N cons operations followed by N uncons operations, or snoc-then-uncons, etc.

### PR DESCRIPTION
**Pull request by ethul**
Benchmarks for snoc then uncons and also N cons followed by N uncons.

Resolves #5

### CODE REVIEW

**Comment by ethul** [comment]
@paf31 Look good to merge?

**Comment by paf31** [comment]
Looks great, thanks!

Sent from my iPhone

**Comment by ethul** [comment]
Great. Welcome!

**Comment by paf31** [comment]
These are one-snoc-one-uncons, right? I'd also be interested to see N batched snocs followed by N batches unconses. I'll try to run it myself to get more experience with benchotron. That might also explain why List wins, because the list size is always 1?

**Comment by ethul** [comment]
The n-cons-uncons one should be doing N cons and then N unions for each iteration of the benchmark where N is the size of the random array.

I thought this was doing what we want.

**Comment by paf31** [comment]
I'm looking at snoc-uncons. It looks like it's doing one at a time.

**Comment by ethul** [comment]
Right, the snoc-uncons does do 1 at a time. I can add an N snoc N uncons too.

**Comment by ethul** [comment]
I've added the N snoc-uncons in PR #7

**Pull request merged**
